# 第25章 进程的终止

## 25.1进程的终止

通常,进程有两种终止方式。

其一为异常(abnormal)终止,由对一信号的接收而引发,该信号的默认动作为终止当前进程,可能产生核心转储(core dump) 。

此外,进程可使用\_exit()系统调用正常(normally)终止。

```c
#include <unistd.h>
void _exit(status);
```

\_exit()的 status 参数定义了进程的终止状态(termination status),父进程可调用 wait()
以获取该状态。虽然将其定义为 int 类型,但仅有低 8 位可为父进程所用。
调用\_exit()的程序总会成功终止(即,\_exit()从不返回)。



程序一般不会直接调用\_exit(),而是调用库函数 exit(),它会在调用_exit()前执行各种动作。 

```c
#include <stdlib.h>
void exit(int status);
```

exit()会执行的动作如下。

- 调用退出处理程序(通过 atexit()和 on_exit()注册的函数),其执行顺序与注册顺序相反(见 25.3 节)。
-  刷新 stdio 流缓冲区。
-  使用由 status 提供的值执行_exit()系统调用。



程序的另一种终止方法是从 main()函数中返回(return),执行 return n 等同于执行对 exit(n)的调用,因为调用 main()的运行时函数会将 main()的返回值作为 exit()的参数。



## 25.2 进程终止的细节

无论进程是否正常终止，都会发生以下的动作：

- 释放资源，如文件描述符、目录流
- 如果该进程是一个管理终端的进程，将会向终端前台的进程组中的每个进程发送 SIGHUP 信号，并脱离与终端的会话。



## 25.3 退出处理程序

若某一进程中使用了一个应用程序库，那么在进程终止前该库需要自动执行一些清理工作。这个时候就要用到退出处理程序，它可以在程序中的任何一段注册，调用exit()正常终止时会自动执行，直接调用_exit()或者收到信号异常终止时不会。

> 可以为信号设置信号处理器，在其中设置标志位，然后主程序据此调用exit()（exit()非线程安全函数，所以不可在信号处理器中调用）。
>
> SIGKILL总是采用默认设置，这也是尽量要少用它的原因。建议使用SIGTERM

#### 注册退出处理程序

```c
#include <stdlib.h>
int atexit(void(*func)(void))  //Returns 0 on success,or nonzero on error
```

该函数将func加入到函数列表里去，进程终止时会调用该函数列表。

你可以注册多个退出处理程序，甚至多次向函数列表里添加同一函数。在执行函数列表时，执行顺序与注册顺序相反。这很符合逻辑，因为先注册的往往执行的是更基本的清理工作，要放到最后进行。

如果有任一退出处理程序无法返回（调用了_exit或收到信号异常终止），那么就不会再调用剩余的处理程序。

通过fork() 创建的子进程会继承父进程注册的退出处理函数。而进程调用exec()时，会移除所有已注册的退出处理程序。

atexit()有两个局限性：

其一，退出处理程序在执行时无法获知传递给exit()的状态

其二，无法指定参数，这样退出处理程序就无法根据参数执行不同的动作

为摆脱这些限制，glibc提供了一个（非标准的）替代方法：

```c
#define _BSD_SOURCE
#include <stdlib.h>
int on_exit(void(*func)(int,void*),void*arg);   //Returns 0 on success,or nonzero on error
```

func指向如下类型的函数：

```c
void func(int status,void* arg)
{
    /*Perform cleanup actions*/
}
```

其中status是调用给exit()的参数，会自动给func，不必担心。



## 25.4 fork()、stdio缓冲区以及_exit()之间的交互

代码：

```cpp
#include <iostream>
#include <unistd.h>
#include "myerror.h"

int main(int argc,char* argv[])
{
    std::cout <<"cout hello world " <<std::endl;
    printf("printf hello world\n");
    write(STDOUT_FILENO,"Ciao\n",5);

    if (fork()==-1){
        myerr("fork");
    }

    exit(EXIT_SUCCESS);
}

```

演示：

```
[username@piu something]$ ./fork_and_buffer
cout hello world
printf hello world
Ciao
[username@piu something]$ ./fork_and_buffer > a
[username@piu something]$ cat a
cout hello world
Ciao
printf hello world
printf hello world
```

这里把输出重定向到 a 之后，重新打印了两遍 printf hello world ，这是为什么呢？

*第一次未重定向时：*

printf()默认是行缓冲，立即打印出来了。

*第二次重定向后：*

printf()默认为块缓冲，缓冲区是维护在进程的用户空间内存中的。fork()时，父进程字符串仍存在缓冲区中内，且该缓冲区被子进程同样地复制了一份。在exit(EXIT_SUCCESS)后，父子进程刷新各自的缓冲区，于是两个进程中缓冲区的内容都被输出了出来。

**可以用以下任一方法来避免重复的输出结果：**

- 作为针对 stdio 缓冲区问题的特定解决方案,可以在调用 fork()之前使用函数 fflush()来刷新 stdio 缓冲区。

  作为另一种选择,也可以使用 setvbuf()和 setbuf()来关闭 stdio 流的缓冲功能。

- 子进程调用_exit()退出而非 exit()



ps: write() 的输出并未出现两次，是因为write()会将数据直接传给内核缓冲区，fork()不会复制这一缓冲区。为什么write()的结果会先于fork()的原因也找到了，因为write()会将数据立即传给内核高速缓冲，而 printf() 的输出则需要等到 exit() 刷新 stdio 缓冲区时。

